baseURL = 'https://valchales.github.io/'
languageCode = 'es-ar'
title = 'Valchales'
theme = 'hugo-blog-awesome'

[params] 
  copyright = "© 2024 Valchales"
  useCDN= "false"
  mathjax = "true"
  defaultColor = "auto"
  description = 'Valchales Blog, viejo.'
  goToTop = true
  rssFeedDescription = "full"

[menu]
  [[menu.main]]
    pageRef = "posts"
    name = "posts"
    url = "/posts"
    weight = 1
  [[menu.main]]
    pageRef = "about"
    name = "about"
    url = "/about/"
    weight = 2

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"