baseURL = 'https://valchales.github.io/'
languageCode = 'en-us'
title = 'El Blog de las Cosas Rancias'
theme = 'holy'

[params] 
  copyright = "© 2024 Valchales"
  mode = "auto"
  useCDN=false
  mathjax = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 2