baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Helamael Blog'
theme = 'archie'

[params] 
  copyright = "© 2024 Helamael"
  mode = "auto"
  useCDN=false
  mathjax = true

[taxonomies]
games = "games"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 2