baseURL = 'https://valchales.github.io/'
languageCode = 'en-us'
title = 'Valchales'
theme = 'hugo-blog-awesome'

[params] 
  copyright = "© 2024 Valchales"
  useCDN= "false"
  mathjax = "true"
  defaultColor = "auto"
  description = 'Blog'
  toc = true
  goToTop = true
  rssFeedDescription = "full"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 2

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"